import "./globals.css";

export const metadata = {
    title: "Hakunta - Index",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased bg-white`}>{children}</body>
        </html>
    );
}
